### ISSUE TITLE
AttributeError: object has no attribute 'items'

### ISSUE THREAD

**Issue by i223t** [rbw/pysnow#154]
Hi,
It looks like examples from the documentation are not working.

Key-value approach is Ok, but QueryBuilder or SN Pass-through raise the errors:

```
start = datetime(1970, 1, 1)
end = datetime.now() - timedelta(days=20)

iterable_content = incident.get(query='numberSTARTSWITHINC0150^sys_created_onBETWEENjavascript:gs.dateGenerate("%s")@javascript:gs.dateGenerate("%s")' % (start, end)).all()
```

generates

>   File "/home/izzet/.local/lib/python3.6/site-packages/pysnow/request.py", line 91, in get
    for key, value in query.items():
AttributeError: 'str' object has no attribute 'items'

```
        start = datetime(1970, 1, 1)
        end = datetime.now() - timedelta(days=20)

        # Query incident records with number starting with 'INC0123', created between 1970-01-01 and 20 days back in time
        qb = (
            pysnow.QueryBuilder()
            .field('number').starts_with('INC0123')
            .AND()
            .field('sys_created_on').between(start, end)
            .AND()
            .field('sys_updated_on').order_descending()
        )

        iterable_content = incident.get(query=qb).all()
```

generates:

> File "/home/izzet/.local/lib/python3.6/site-packages/pysnow/request.py", line 91, in get
>     for key, value in query.items():
> AttributeError: 'QueryBuilder' object has no attribute 'items'

**Comment by nplebanskyi** [comment]
I've got the same issue.

**Comment by rbw** [comment]
Looking into this shortly

**Comment by rbw** [comment]
This was due to a regression introduced with #147.

It's fixed in 0.7.16, now available on pypi.

Btw - if you're building something new on python3.7+, make sure to check out [snow](https://github.com/rbw/snow), a new ServiceNow library I'm working on. It's soon in beta.

**Comment by rbw** [comment]
Thanks for reporting

**Comment by i223t** [comment]
Thanks man. 
The project is awesome, you are doing a great job!
